experiment_name: "rank128_evqa_adalora_llava_evqa"
alg_name: "LoRA"
name: liuhaotian/llava-v1.5-7b
model_name: "llava"
model_class: LlamaForCausalLM
tokenizer_class: LlamaTokenizer
tokenizer_name: liuhaotian/llava-v1.5-7b
cache_dir: models/cache
device: 0
cpu_copy: True

lora_type: "adalora"
layers: [7]
num_steps: 70
batch_size: 1
max_length: 30
lr: 5e-4
weight_decay: 0
kl_factor: 0
rank: 128
lora_alpha: 128
lora_dropout: 0
norm_constraint: false
target_modules: ["up_proj", "down_proj"]
exclude_modules: []
model_parallel: false

coco_image: data
rephrase_image: data
result_dir: outputs/rank128_evqa
train_annotation_path: data/editing-data/vqa/vqa_train.json
eval_annotation_path: data/editing-data/vqa/vqa_eval.json

all_metrics_name: "llava_adalora_r128_evqa.jsonl"
json_dir: outputs/rank128_evqa/jsonl
continuous_sample: 1

real_world_eval: false
api_key: null
